platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'iosfinal2018' do
use_frameworks!
pod 'Eureka'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire', '~> 4.7'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'SwiftyJSON', '~> 4.0'
pod 'SwiftMultiSelect'
pod 'SkyFloatingLabelTextField', '~> 3.0'
end
